### PR TITLE
Bump linux version to 21.6

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
```
[instantclient-basic-linux.x64-21.6.0.0.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of instantclient-basic-linux.x64-21.6.0.0.0.zip or
        instantclient-basic-linux.x64-21.6.0.0.0.zip.zip, and cannot find instantclient-basic-linux.x64-21.6.0.0.0.zip.ZIP, period.
```
The download url I see is:
```
https://download.oracle.com/otn_software/linux/instantclient/216000/instantclient-basic-linux.x64-21.6.0.0.0dbru.zip
```

**Comment by dhirschfeld** [comment]
It looks like this package dynamically downloads and unzips the client at *runtime*?!

I'm curious why the contents of the zip file aren't unpacked and installed at *build* time like ~every other package?

**Comment by dhirschfeld** [comment]
It appears that the license allows for redistribution:
> License Rights and Restrictions
>
> Oracle grants to You, as a recipient of this Program, a nonexclusive,
nontransferable, limited license to, subject to the conditions stated
herein, (a) internally use the unmodified Programs for the purposes of
developing, testing, prototyping and demonstrating your applications,
and running the Programs for your own internal business operations;
and ***(b) redistribute unmodified Programs and Programs Documentation,
under the terms of this License, provided that You do not charge Your
end users any additional fees for the use of the Programs. You may
make copies of the Programs to the extent reasonably necessary for
exercising the license rights granted herein and for backup
purposes.***

[BASIC_LICENSE.txt](https://github.com/conda-forge/oracle-instant-client-feedstock/files/9069009/BASIC_LICENSE.txt)

**Comment by beckermr** [comment]
The license has not allowed redistribution in the past, hence the runtime installation.

**Comment by beckermr** [comment]
Why did you remove the osx build?

**Comment by dhirschfeld** [comment]
> Why did you remove the osx build?

Just because that version hasn't changed but they share a build number. Figured it was easiest to disable until a new osx version was published. Could also just bump the build and have `21.6` start at build 3 if you thought that was better?

**Comment by beckermr** [comment]
I am going to forget and then we'll be missing a package. A bump is fine by me.

**Comment by dhirschfeld** [comment]
> *The license has not allowed redistribution in the past, hence the runtime installation.*

Given that it appears that has changed would you accept a (separate) PR to actually install the package in the build?

**Comment by beckermr** [comment]
I am not feeling very confident about licensing here so I'd prefer to keep things as they are.

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
> I am not feeling very confident about licensing here so I'd prefer to keep things as they are.

With oracle, that's fair enough.

**Comment by dhirschfeld** [comment]
It's missing the `dbru` suffix:
```
export PREFIX=/home/conda/feedstock_root/build_artifacts/oracle-instant-client_1657279044961/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/oracle-instant-client_1657279044961/test_tmp
++++ mkdir -p /home/conda/feedstock_root/build_artifacts/oracle-instant-client_1657279044961/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/oracle_instant_client
++++ pushd /home/conda/feedstock_root/build_artifacts/oracle-instant-client_1657279044961/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/oracle_instant_client
++++ curl -Ls https://download.oracle.com/otn_software/linux/instantclient/216000/instantclient-basic-linux.x64-21.6.0.0.0.zip
++++ unzip -qq instantclient-basic-linux.x64-21.6.0.0.0.zip
[instantclient-basic-linux.x64-21.6.0.0.0.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of instantclient-basic-linux.x64-21.6.0.0.0.zip or
        instantclient-basic-linux.x64-21.6.0.0.0.zip.zip, and cannot find instantclient-basic-linux.x64-21.6.0.0.0.zip.ZIP, period.
Tests failed for oracle-instant-client-21.6.0.0.0-ha770c72_3.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

I'm not sure I understand exactly how that's set (or not) 🤔

**Comment by dhirschfeld** [comment]
Looks like that did it.

**Pull request merged**
